#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

PROJECT_PATH=""

usage() {
  echo -e "Usage: $0 -p <project_path>"
  echo ""
  echo -e "  Detects the project language and generates a sonar-project.properties"
  echo -e "  file ready to use with 'make analyze'."
  echo ""
  echo -e "  -p  Path to the project ${RED}(required)${NC}"
  echo -e "  -h  Show this help"
  exit 1
}

while getopts "p:h" opt; do
  case "$opt" in
    p) PROJECT_PATH="$OPTARG" ;;
    h) usage ;;
    *) usage ;;
  esac
done

if [ -z "$PROJECT_PATH" ]; then
  echo -e "${RED}Error: -p <project_path> is required.${NC}"
  usage
fi

PROJECT_PATH="$(realpath "$PROJECT_PATH")"

if [ ! -d "$PROJECT_PATH" ]; then
  echo -e "${RED}Error: '$PROJECT_PATH' is not a directory.${NC}"
  exit 1
fi

OUTPUT_FILE="${PROJECT_PATH}/sonar-project.properties"

if [ -f "$OUTPUT_FILE" ]; then
  echo -e "${YELLOW}sonar-project.properties already exists in this project.${NC}"
  read -rp "  Overwrite? (yes/no): " confirm
  [ "$confirm" = "yes" ] || { echo "Aborted."; exit 0; }
fi

DIR_NAME="$(basename "$PROJECT_PATH")"
PROJECT_KEY="$(echo "$DIR_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd '[:alnum:]_.-')"

# ── Language detection ────────────────────────────────────────────────────────
detect_language() {
  # Check for language-specific marker files first (most reliable)
  [ -f "${PROJECT_PATH}/pom.xml" ] || [ -f "${PROJECT_PATH}/build.gradle" ] && { echo "java"; return; }
  [ -f "${PROJECT_PATH}/go.mod" ]                                             && { echo "go"; return; }
  [ -f "${PROJECT_PATH}/composer.json" ]                                      && { echo "php"; return; }
  [ -f "${PROJECT_PATH}/requirements.txt" ] \
    || [ -f "${PROJECT_PATH}/pyproject.toml" ] \
    || [ -f "${PROJECT_PATH}/setup.py" ]                                      && { echo "python"; return; }
  [ -f "${PROJECT_PATH}/package.json" ]                                       && { echo "js"; return; }

  # Fallback: count source files by extension
  local java_count php_count py_count go_count js_count ts_count
  java_count=$(find "$PROJECT_PATH" -name "*.java" 2>/dev/null | wc -l)
  php_count=$(find  "$PROJECT_PATH" -name "*.php"  2>/dev/null | wc -l)
  py_count=$(find   "$PROJECT_PATH" -name "*.py"   2>/dev/null | wc -l)
  go_count=$(find   "$PROJECT_PATH" -name "*.go"   2>/dev/null | wc -l)
  js_count=$(find   "$PROJECT_PATH" -name "*.js"   -not -path "*/node_modules/*" 2>/dev/null | wc -l)
  ts_count=$(find   "$PROJECT_PATH" -name "*.ts"   -not -path "*/node_modules/*" 2>/dev/null | wc -l)

  local max=0 lang="unknown"
  for pair in "java:$java_count" "php:$php_count" "python:$py_count" "go:$go_count" "js:$((js_count + ts_count))"; do
    local l="${pair%%:*}" c="${pair##*:}"
    [ "$c" -gt "$max" ] && { max=$c; lang=$l; }
  done
  echo "$lang"
}

LANGUAGE="$(detect_language)"

echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}  SonarQube Project Init${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""
echo -e "  Project : ${YELLOW}${PROJECT_PATH}${NC}"
echo -e "  Key     : ${YELLOW}${PROJECT_KEY}${NC}"
echo -e "  Language: ${YELLOW}${LANGUAGE}${NC}"
echo ""

# ── Generators ────────────────────────────────────────────────────────────────
write_header() {
  cat <<EOF
# Generated by code-gate init-project.sh
# sonar-project.properties — $(date +%Y-%m-%d)

sonar.projectKey=${PROJECT_KEY}
sonar.projectName=${DIR_NAME}
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8

EOF
}

write_exclusions() {
  cat <<'EOF'
sonar.exclusions=\
  **/.git/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**

EOF
}

write_js() {
  cat <<'EOF'
# ── JavaScript / TypeScript ───────────────────────────────────────────────────
# Generate coverage report before running make analyze:
#   jest --coverage --coverageReporters=lcov
#   output: coverage/lcov.info

sonar.exclusions=\
  **/.git/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/.next/**,\
  **/build/**,\
  **/coverage/**,\
  **/*.min.js

sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts
sonar.coverage.exclusions=**/*.test.*,**/*.spec.*,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
EOF
}

write_python() {
  cat <<'EOF'
# ── Python ────────────────────────────────────────────────────────────────────
# Generate coverage report before running make analyze:
#   pip install pytest-cov
#   pytest --cov=src --cov-report=xml
#   output: coverage.xml

sonar.exclusions=\
  **/.git/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/.venv/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**

sonar.tests=tests
sonar.test.inclusions=**/test_*.py,**/*_test.py
sonar.coverage.exclusions=**/test_*.py,**/*_test.py,**/tests/**

sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
EOF
}

write_java() {
  local build_tool="Maven"
  [ -f "${PROJECT_PATH}/build.gradle" ] && build_tool="Gradle"

  if [ "$build_tool" = "Maven" ]; then
    cat <<'EOF'
# ── Java (Maven + JaCoCo) ─────────────────────────────────────────────────────
# Add JaCoCo to pom.xml and generate coverage report before running make analyze:
#   mvn test
#   output: target/site/jacoco/jacoco.xml
#
# pom.xml plugin:
#   <plugin>
#     <groupId>org.jacoco</groupId>
#     <artifactId>jacoco-maven-plugin</artifactId>
#     <version>0.8.11</version>
#     <executions>
#       <execution><goals><goal>prepare-agent</goal></goals></execution>
#       <execution>
#         <id>report</id><phase>test</phase>
#         <goals><goal>report</goal></goals>
#       </execution>
#     </executions>
#   </plugin>

sonar.exclusions=\
  **/.git/**,\
  **/target/**,\
  **/build/**,\
  **/coverage/**

sonar.tests=src/test/java
sonar.test.inclusions=**/*Test.java,**/*IT.java,**/*Spec.java
sonar.coverage.exclusions=**/*Test.java,**/*IT.java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
EOF
  else
    cat <<'EOF'
# ── Java (Gradle + JaCoCo) ────────────────────────────────────────────────────
# Add JaCoCo to build.gradle and generate coverage report before running make analyze:
#   ./gradlew test jacocoTestReport
#   output: build/reports/jacoco/test/jacocoTestReport.xml
#
# build.gradle:
#   plugins { id 'jacoco' }
#   jacocoTestReport {
#     reports { xml.required = true }
#   }
#   test { finalizedBy jacocoTestReport }

sonar.exclusions=\
  **/.git/**,\
  **/build/**,\
  **/coverage/**

sonar.tests=src/test/java
sonar.test.inclusions=**/*Test.java,**/*IT.java,**/*Spec.java
sonar.coverage.exclusions=**/*Test.java,**/*IT.java

sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
EOF
  fi
}

write_go() {
  cat <<'EOF'
# ── Go ────────────────────────────────────────────────────────────────────────
# Generate coverage report before running make analyze:
#   go test ./... -coverprofile=coverage.out
#   output: coverage.out

sonar.exclusions=\
  **/.git/**,\
  **/vendor/**,\
  **/dist/**,\
  **/build/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
EOF
}

write_php() {
  cat <<'EOF'
# ── PHP (PHPUnit) ─────────────────────────────────────────────────────────────
# Add clover report to phpunit.xml and generate coverage before running make analyze:
#   ./vendor/bin/phpunit --coverage-clover coverage/clover.xml
#   output: coverage/clover.xml
#
# phpunit.xml:
#   <coverage>
#     <report>
#       <clover outputFile="coverage/clover.xml"/>
#     </report>
#   </coverage>

sonar.exclusions=\
  **/.git/**,\
  **/vendor/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**

sonar.tests=tests
sonar.test.inclusions=**/*Test.php,**/Test*.php
sonar.coverage.exclusions=**/*Test.php,**/Test*.php,**/tests/**

sonar.php.coverage.reportPaths=coverage/clover.xml
EOF
}

write_unknown() {
  cat <<'EOF'
# ── Language not detected ─────────────────────────────────────────────────────
# Uncomment and configure the block for your language.
# See config/sonar-project.properties.template for all options.

# sonar.tests=tests
# sonar.test.inclusions=
# sonar.coverage.exclusions=
EOF
}

# ── Write file ────────────────────────────────────────────────────────────────
{
  write_header
  case "$LANGUAGE" in
    js)      write_js ;;
    python)  write_python ;;
    java)    write_java ;;
    go)      write_go ;;
    php)     write_php ;;
    *)       write_exclusions; write_unknown ;;
  esac
  echo ""
  echo "# SonarQube server (overridden by analyze.sh)"
  echo "sonar.host.url=http://localhost:9000"
} > "$OUTPUT_FILE"

echo -e "${GREEN}sonar-project.properties created at:${NC}"
echo -e "  ${YELLOW}${OUTPUT_FILE}${NC}"
echo ""
echo -e "Review the file, generate your coverage report, then run:"
echo -e "  ${CYAN}make analyze DIR=${PROJECT_PATH}${NC}"
echo ""
